# Generated by Django 4.0.6 on 2022-07-21 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeComponent', models.CharField(max_length=50)),
                ('typeEntrada', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('existencia', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComponentI',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Computer.component')),
                ('marca', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
            ],
            bases=('Computer.component',),
        ),
        migrations.CreateModel(
            name='ComponentO',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Computer.component')),
                ('marca', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
            ],
            bases=('Computer.component',),
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOrden', models.IntegerField()),
                ('computadoraId', models.ManyToManyField(to='Computer.computadora')),
            ],
        ),
        migrations.CreateModel(
            name='Altavoz',
            fields=[
                ('componento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Computer.componento')),
                ('existencia', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateField(auto_now=True)),
            ],
            bases=('Computer.componento',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('componento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Computer.componento')),
                ('existencia', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateField(auto_now=True)),
            ],
            bases=('Computer.componento',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('componenti_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Computer.componenti')),
                ('existencia', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateField(auto_now=True)),
            ],
            bases=('Computer.componenti',),
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('componenti_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Computer.componenti')),
                ('existencia', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateField(auto_now=True)),
            ],
            bases=('Computer.componenti',),
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('componenti_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Computer.componenti')),
                ('existencia', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('fechaIngreso', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateField(auto_now=True)),
            ],
            bases=('Computer.componenti',),
        ),
        migrations.AddField(
            model_name='computadora',
            name='idAltavoz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.altavoz'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='idMonitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.monitor'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='idMouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.mouse'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='idProcesador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.procesador'),
        ),
        migrations.AddField(
            model_name='computadora',
            name='idTeclado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.teclado'),
        ),
    ]
