# Generated by Django 4.0.6 on 2022-07-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0003_alter_computadora_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
