# Generated by Django 4.0.6 on 2022-07-25 16:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0004_orden_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='computadoraId',
        ),
        migrations.AddField(
            model_name='orden',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderDetailComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalOrder', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('computadoraId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.computadora')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Computer.orden')),
            ],
        ),
    ]
