# Generated by Django 4.0.6 on 2022-07-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0005_remove_orden_computadoraid_orden_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetailcomputer',
            old_name='order',
            new_name='orderId',
        ),
    ]
