# Generated by Django 4.0.6 on 2022-07-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Computer', '0006_rename_order_orderdetailcomputer_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailcomputer',
            name='existencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
